# Generated by Django 6.0.3 on 2026-04-14 00:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0003_alter_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('digitable_line', models.CharField(max_length=100, unique=True)),
                ('our_number', models.CharField(max_length=64)),
                ('document_number', models.CharField(max_length=64)),
                ('bank_code', models.CharField(max_length=4)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_document', models.CharField(max_length=14)),
                ('beneficiary_agency', models.CharField(max_length=4)),
                ('beneficiary_account', models.CharField(max_length=16)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_document', models.CharField(max_length=14)),
                ('payer_address', models.CharField(max_length=200)),
                ('payer_city', models.CharField(max_length=50)),
                ('payer_state', models.CharField(max_length=50)),
                ('payer_zipcode', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('PAID', 'paid'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=12)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionmodel')),
            ],
        ),
    ]
