# Generated by Django 6.0.3 on 2026-04-20 14:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=44, unique=True)),
                ('digitable_line', models.CharField(max_length=54, unique=True)),
                ('our_number', models.CharField(max_length=20, unique=True)),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('bank_code', models.CharField(default='120', max_length=3)),
                ('currency_code', models.CharField(default='9', max_length=1)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(db_index=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_document', models.CharField(max_length=18)),
                ('beneficiary_agency', models.CharField(max_length=10)),
                ('beneficiary_account', models.CharField(max_length=20)),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_document', models.CharField(max_length=18)),
                ('payer_address', models.CharField(max_length=200)),
                ('payer_city', models.CharField(max_length=100)),
                ('payer_state', models.CharField(max_length=2)),
                ('payer_zipcode', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=12)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
