# Generated by Django 6.0.3 on 2026-04-16 14:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0001_initial'),
        ('transaction', '0004_alter_transactionmodel_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='bank_code',
            field=models.CharField(default='120', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='barcode',
            field=models.CharField(max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_account',
            field=models.CharField(default='99999918', max_length=16),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_agency',
            field=models.CharField(default='9918', max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_document',
            field=models.CharField(default='beneficiary document', max_length=14),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_name',
            field=models.CharField(default='beneficiary enterprise name', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='digitable_line',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='instructions',
            field=models.TextField(blank=True, default='Pay at the bank or other financial store'),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='our_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_address',
            field=models.CharField(default='some address', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_city',
            field=models.CharField(default='San Francisco', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_document',
            field=models.CharField(default='000000', max_length=14),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_state',
            field=models.CharField(default='California', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_zipcode',
            field=models.CharField(default='999999', max_length=9),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionmodel'),
        ),
    ]
