# Generated by Django 6.0.3 on 2026-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0002_alter_paymentslipmodel_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='due_date',
            field=models.DateField(),
        ),
    ]
