# Generated by Django 6.0.3 on 2026-04-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_account',
            field=models.CharField(default='99999918', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_agency',
            field=models.CharField(default='9918', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_document',
            field=models.CharField(default='doc number', max_length=18),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_name',
            field=models.CharField(default='beneficiary enterprise name', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='digitable_line',
            field=models.CharField(max_length=51, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_address',
            field=models.CharField(default='some address', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_city',
            field=models.CharField(default='Gramado', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_document',
            field=models.CharField(default='000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_state',
            field=models.CharField(default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='payer_zipcode',
            field=models.CharField(default='95670-000', max_length=9),
        ),
    ]
