# Generated by Django 6.0.3 on 2026-05-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0003_alter_paymentslipmodel_beneficiary_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='digitable_line',
            field=models.CharField(max_length=54, unique=True),
        ),
    ]
