# Generated by Django 6.0.3 on 2026-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0003_alter_paymentslipmodel_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='beneficiary_document',
            field=models.CharField(default='beneficiary document', max_length=20),
        ),
    ]
