# Generated by Django 6.0.3 on 2026-04-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_slip', '0004_alter_paymentslipmodel_beneficiary_document'),
        ('transaction', '0004_alter_transactionmodel_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslipmodel',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactionmodel'),
        ),
    ]
