# Generated by Django 6.0.3 on 2026-03-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_account_accountmodel_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionModel',
        ),
    ]
