# Generated by Django 6.0.3 on 2026-04-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_transaction_transactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('TF', 'Transfer'), ('DP', 'Deposit'), ('WD', 'Withdraw'), ('PM', 'Payment')], max_length=2, null=True),
        ),
    ]
