# Generated by Django 6.0.3 on 2026-04-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_account_accountmodel_and_more'),
        ('transaction', '0003_alter_transactionmodel_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.accountmodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(choices=[('TF', 'Transfer'), ('DP', 'Deposit'), ('WD', 'Withdraw'), ('PM', 'Payment')], max_length=2),
        ),
    ]
