# Generated by Django 6.0.3 on 2026-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='score',
            field=models.PositiveSmallIntegerField(default=740),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 1000)), name='score_between_1_and_1000'),
        ),
    ]
