# Generated by Django 6.0.3 on 2026-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_options_alter_usermodel_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='score',
            field=models.PositiveSmallIntegerField(default=787),
        ),
    ]
