# Generated by Django 6.0.3 on 2026-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_usermodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='score',
            field=models.PositiveSmallIntegerField(default=939),
        ),
    ]
