# Generated by Django 6.0.3 on 2026-03-18 17:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('agency', models.CharField(default='1201', max_length=4)),
                ('number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CA', 'Checking Accounts'), ('SA', 'Saving Accounts')], max_length=2)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortgage_type', models.CharField(choices=[('FHAL', 'FHA Loan'), ('VALN', 'VA Loans'), ('CVTL', 'Conventional Loan'), ('JUBL', 'Jumbo Loan'), ('UDAL', 'USDA Loan')], max_length=4)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(84)])),
                ('due_date', models.CharField(choices=[('10', 'ten'), ('05', 'five'), ('17', 'seventeen'), ('25', 'twenty-five')], default='25', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
