# Generated by Django 6.0.3 on 2026-03-18 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='products.account'),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mortgage',
            constraint=models.UniqueConstraint(fields=('client', 'account'), name='one_client_account'),
        ),
    ]
