# Generated by Django 6.0.3 on 2026-03-18 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_type_account_account_type'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='AccountModel',
        ),
        migrations.RenameModel(
            old_name='Mortgage',
            new_name='MortgageModel',
        ),
    ]
